### ISSUE TITLE
GitHub test workflow

### ISSUE THREAD

**Issue by drowe67** [drowe67/radae#1]
Create GitHub workflow to run ctests on git push.  Would need to build codec2-dev as per README, opus (FARGAN) builds as part of the `make` process.

Skills: GitHub workflow

**Comment by DJ2LS** [comment]
I can assist with this one. 

Some questions:
- Are we just going to run the ctests? 
- Which python versions are we testing? 
- Which operating systems are we testing?

**Comment by drowe67** [comment]
Thanks for considering this one @DJ2LS 

>     * Are we just going to run the ctests?

Yes.  So build (opus), run ctests.
 
>     * Which python versions are we testing?

Whatever comes with Ubuntu 22 would be fine.
 
>     * Which operating systems are we testing?

Just Ubuntu 22 - pls see https://github.com/drowe67/radae#scope.
