### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by barjac** [drowe67/radae#32]
Hello David,
I am trying to package radae for Mageia as a dependency of freedv.

I have several issues, bearing in mind that I am a packager not a programmer.

I cannot see a way to allow for the use of our system opus, so I have temporarily allowed the test package to download and build opus as per default, although to build, it does need -fPIE.

The radae build completes now but creates an empty package since AFAICT there is no 'install' information in the CMakeLists.txt.

Can you please add a Cmake option to allow the system opus?
If there are important differences between your FARGAN build and a 'normal' package build then we can maybe generate a new opus package to provide this feature. 

Could an install section please be added so I can continue?

Thanks, Barry

**Comment by tmiw** [comment]
Also, it's probably premature to package either rade or freedv-gui 2.x given the high number of dependencies and the fluidness of the current code. It may be better to wait until we're closer to an official release of freedv-gui (i.e. not -devel).

**Comment by barjac** [comment]
> Would it be possible to update the opus package to add `--enable-dred` to `./configure`? I don't think that should impact any existing users of opus but I could be wrong.

I will take a look at that - not sure yet what else depends on it.

**Comment by barjac** [comment]
> Also, it's probably premature to package either rade or freedv-gui 2.x given the high number of dependencies and the fluidness of the current code. It may be better to wait until we're closer to an official release of freedv-gui (i.e. not -devel).

It's the high number of dependences that has pushed me to make a start. Its looking like an extra 20 packages that we currently don't have.

I assume that none of the final builds of radae or freedv-gui-2.x will be expected to download from upstreams during package builds as this is strictly not allowed for our official packages.

Please can the option to use system packages be introduced sooner rather than later for build testing? i.e. if a system package is installed then don't try to download and build it.

**Comment by tmiw** [comment]
That'll probably be up to the project team, I think, but FWIW the number of dependencies will likely go down once the planned C port is done.

**Comment by drowe67** [comment]
Hi @barjac as per the Scope statement at the top of the README this repo **should not be considered** for packaging.  There are good reasons for this. Suitable code for Linux packaging will come later.  The current FreeDV PLT policy is for Linux users to install manually.

**Comment by barjac** [comment]
OK understood, so are you saying that you will not be recommending that any Linux packaging should be done for 2.x before the requirement for python3-torch is removed?
