### ISSUE TITLE
Building Opus code with vector acceleration

### ISSUE THREAD

**Issue by drowe67** [drowe67/radae#7]
Work out a sensible way to handle the use of hardware vector acceleration, and remove these warnings:
```
cd radae/build
make
<snip>
/home/david/opus/dnn/nnet.h:157:2: warning: #warning "Only SSE and SSE2 are available. On newer machines, enable SSSE3/AVX/AVX2 using -march= to get better performance" [-Wcpp]
  157 | #warning "Only SSE and SSE2 are available. On newer machines, enable SSSE3/AVX/AVX2 using -march= to get better performance"
```
Scope includes the opus build and radae C code
Some examples of how we have handled this previously: https://github.com/drowe67/LPCNet/blob/master/CMakeLists.txt
Opus code and radae C code should be built with appropriate levels of acceleration for machine in use (can be manually or automatically configured)

Skills: cmake, C

**Comment by drowe67** [comment]
from Jean-Marc: add these cflags `--march=native` or `march=haswell`

**Comment by tmiw** [comment]
I'm fairly sure that FARGAN is already being built with vector acceleration, it's just that `fargan.h` is also including internal Opus .h files that are checking for this (hence the spurious warnings). If we really want to suppress these warnings, we can generate a wrapper .h file as part of the `cmake` invocation (and included by `lpcnet_demo.c` and other files as appropriate) that pulls the Opus `config.h` in. Let me know and I'll go ahead and create a PR for this.

**Comment by drowe67** [comment]
Thanks for the tip - I think I've worked out a way to prevent the warning in #33
