### ISSUE TITLE
Opus build automation

### ISSUE THREAD

**Issue by drowe67** [drowe67/radae#8]
As per TODO in `src/CMakeLists.txt` automate building `libopus.a`
Build opus under radae as part of `cmake ..`
Automagically work out what files to put in `libopus.a`
Update `README.md`
Skills: cmake

**Comment by tmiw** [comment]
Question--anything special about the `opus-ng` branch? Currently there doesn't seem to be anything specifically implemented in there, just that it's significantly behind `main`.

**Comment by drowe67** [comment]
Yes it's where I was told the `fargan` vocoder lives, which is a very different codec to opus.

**Comment by tmiw** [comment]
> Yes it's where I was told the `fargan` vocoder lives, which is a very different codec to opus.

Looks like `main` has it too? At least according to https://github.com/xiph/opus/blob/main/dnn/torch/fargan/README.md, anyway. Some functions were renamed between `opus-ng` and `main`, though, so it won't be as simple as just using `main` instead.

**Comment by drowe67** [comment]
I messaged the author and he said we should indeed use `main` :+1: Hopefully nothing will break, the ctests should trap any issues.

**Comment by tmiw** [comment]
I started working on this a little bit but I ran into the following issue:

```
[ 90%] Building C object src/CMakeFiles/lpcnet_demo.dir/lpcnet_demo.c.o
In file included from /Users/mooneer/devel/radae/src/lpcnet_demo.c:39:
In file included from /Users/mooneer/devel/radae/build/build_opus-prefix/src/build_opus/dnn/fargan.h:31:
In file included from /Users/mooneer/devel/radae/build/build_opus-prefix/src/build_opus/dnn/fargan_data.h:5:
/Users/mooneer/devel/radae/build/build_opus-prefix/src/build_opus/dnn/nnet.h:157:2: warning: "Only SSE and SSE2 are available. On newer machines, enable SSSE3/AVX/AVX2 using -march= to get better performance" [-W#warnings]
#warning "Only SSE and SSE2 are available. On newer machines, enable SSSE3/AVX/AVX2 using -march= to get better performance"
 ^
1 warning generated.
make[2]: *** No rule to make target `external/dist/lib/libopus.dylib', needed by `src/lpcnet_demo'.  Stop.
make[1]: *** [src/CMakeFiles/lpcnet_demo.dir/all] Error 2
make: *** [all] Error 2
```

I need to shelve my changes and make sure I can build on my current environment with the current repo without that warning before I can continue, but not sure I'll be able to get to this today.

**Comment by drowe67** [comment]
Thanks for taking a look at this one. There's no rush, take your time.

Is the problem you are referring to the warning? I get that warning too when I build normally using the current `./configure` etc opus process, see #7.  TBH I don't think it's an actual problem, as it runs just fine on the machines I have tested.   Maybe run #7 to ground after the basic build in this Issue is running.

We don't need OSX support right now if that's a problem (see Scope section in README).

**Comment by tmiw** [comment]
I have a PR open with the needed changes at https://github.com/drowe67/radae/pull/12 if you'd like to take a look. 👍
